import React, { Component } from 'react';
import Container from 'react-bootstrap/Container';
export default class Sales extends Component {
  render() {
    return (
      <Container>
        <h1>Sales</h1>
        <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque feugiat arcu id lacus tincidunt fringilla. Cras ut tortor commodo, mattis erat ut, accumsan leo. Vivamus quam orci, blandit in fermentum placerat, ultricies vel est. Nullam egestas nibh ac ligula efficitur gravida. Integer rutrum enim nec dui sodales vehicula. Cras purus enim, semper et quam sed, malesuada elementum nisi. Vestibulum odio est, venenatis vel mauris sed, semper ornare leo. Nullam consectetur luctus lectus, ac viverra arcu fermentum nec. Etiam sodales lacus nulla, vitae porttitor arcu placerat vitae. Morbi fringilla sapien eget nisi eleifend mattis.</p>
        <p>Ut vel dignissim neque. Mauris mattis scelerisque urna, id pellentesque metus condimentum a. Nullam tempus ante id nisl ornare, non pulvinar eros tincidunt. Vivamus pretium, odio id porttitor elementum, est erat posuere enim, vel congue tortor ipsum mattis mauris. Suspendisse sed egestas ex. Sed tempor porttitor lectus. Donec maximus, mauris et cursus varius, purus nisi consequat lectus, in rhoncus velit libero a dolor. Mauris ut erat turpis. Vestibulum tellus diam, porttitor et facilisis ut, commodo et ante. Pellentesque id hendrerit augue, at vestibulum massa. Nullam blandit mauris sed blandit efficitur. Nulla id purus facilisis augue pretium facilisis et at sapien. Suspendisse dapibus efficitur diam, eget fermentum augue sollicitudin non. Proin varius vehicula purus, eu hendrerit ante lacinia condimentum. Etiam aliquet ante ut consectetur rutrum.</p>
        <p>Quisque tincidunt ac diam eu placerat. Pellentesque varius lectus libero, ut pulvinar nisl congue ultricies. Maecenas nec ornare nulla, fermentum tincidunt mi. Morbi fringilla, metus consectetur varius semper, felis augue vehicula sapien, ac gravida felis justo sed leo. Vivamus nibh leo, laoreet sed sagittis at, vulputate eget metus. Aenean porta a ligula a ornare. Donec et quam mauris. Nullam lacinia, massa et lobortis consectetur, arcu tellus tempus justo, rutrum auctor ante quam ut risus. Quisque at laoreet neque, eu consectetur odio. Proin mollis porta ex et volutpat. Quisque id tempus odio. Nunc ante diam, lobortis sed justo at, aliquet ornare dui. Mauris porttitor vulputate justo, ut rutrum quam ultricies ut. Donec placerat felis id turpis elementum, ut porta velit semper.</p>
        <p>Curabitur viverra id felis vel pellentesque. Cras quis enim volutpat, ornare nisl sed, interdum diam. Proin nibh nulla, condimentum vel arcu at, vehicula faucibus mi. Suspendisse ut posuere erat. Ut maximus lobortis molestie. Aliquam interdum felis sed tempus lacinia. Ut in tristique orci. Cras at finibus nulla. Sed blandit mollis venenatis. Proin efficitur elit lacus, quis blandit mauris interdum id. Nulla neque augue, consectetur ut tortor ornare, malesuada ullamcorper magna. In pretium tincidunt velit, in accumsan sem venenatis id. Ut sit amet urna lectus. Donec iaculis lectus eu quam efficitur faucibus. In hac habitasse platea dictumst.</p>
        <p>Aenean eget ante eget ex dictum faucibus. Quisque mollis ultricies pretium. Maecenas ac fermentum augue, in vulputate lacus. Vestibulum nisl nulla, consequat eu lacus eget, lobortis aliquam diam. Integer a ligula a massa imperdiet interdum eu eget neque. Sed non est et lectus hendrerit pulvinar et fringilla tortor. Suspendisse blandit tempus leo. In et fermentum tellus. Fusce auctor, risus sit amet tincidunt dictum, neque magna aliquet dolor, at consectetur leo mi ac sem. Pellentesque suscipit tempus urna a semper. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla in sem congue, accumsan dolor id, tincidunt est. Cras at lacus in odio placerat porttitor et congue dui. Quisque efficitur pharetra purus, ac dapibus leo aliquam sed. Nulla non dictum nisl, non dapibus diam.</p>
      </Container>
    )
  }
}
